# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Manual release build publishing developer packages.

variables:
- template: Config/settings.yaml
- name: Version.Revision
  value: $[counter(variables['MRTKVersion'], 1)]
- name: Version.PreReleaseRevision
  value: $[counter(variables['MRTKReleaseTag'], 1)]

trigger: none # disable CI
pr: none # disable PR validation

jobs:
- job: Packing
  pool:
    vmImage: windows-latest
  steps:
  - pwsh: Write-Host "##vso[build.updatebuildnumber]$(MRTKVersion)-$(MRTKReleaseTag).$(Version.PreReleaseRevision)"
    displayName: 'Set Build Number'
  - template: Templates/upm.yaml
    parameters:
      buildNumber: $(Version.Revision)
      previewTag: $(MRTKReleaseTag).$(Version.PreReleaseRevision)
