# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

parameters:
  # The output file that will contain the list of changed files in this
  # pull request.
  changesFile: ''

steps:
- task: PowerShell@2
  displayName: 'Get PullRequest Changes'
  inputs:
    pwsh: true
    targetType: filePath
    filePath: ./Pipelines/Scripts/gitchanges.ps1
    arguments: >
      -TargetBranch: '$(System.PullRequest.TargetBranch)'
      -OutputFile: '${{ parameters.changesFile }}'
      -RepoRoot: '$(Build.SourcesDirectory)'
