# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

parameters:
  # If true, validation scripts will only be run on the set of changed files
  # associated with a given pull request. Note that this is only valid to use
  # for pull request validation, since this functionality requires a pull request
  # ID in order to determine the two commits to diff.
  scopedValidation: false
  # The file containing the list of changes, used if scopedValidation is true.  
  changesFile: ''

steps:
- ${{ if eq(parameters.scopedValidation, false) }}:
  - task: PowerShell@2
    displayName: 'Global code validation'
    inputs:
      pwsh: true
      targetType: filePath
      filePath: ./Pipelines/Scripts/validatecode.ps1
      arguments: >
        -Directory: '$(Build.SourcesDirectory)'
- ${{ if eq(parameters.scopedValidation, true) }}:
  - task: PowerShell@2
    displayName: 'Scoped code validation'
    inputs:
      pwsh: true
      targetType: filePath
      filePath: ./Pipelines/Scripts/validatecode.ps1
      arguments: >
        -Directory: '$(Build.SourcesDirectory)'
        -ChangesFile: '${{ parameters.changesFile }}'
