# [Template] Build project inside Unity.

parameters:
- name: UnityVersion
  type: string

- name: BuildTarget
  type: string
  values:
    - StandaloneWindows64
    - WSAPlayer
    - Android

- name: CommandLineBuildMethod
  type: string

- name: PathToProject
  type: string

- name: OutputPath
  type: string

- name: AdditionalArguments
  type: string
  default: ''

steps:
- powershell: |
    $logFile = Join-Path $(Agent.TempDirectory) "build_${{ parameters.BuildTarget }}.log"
    Start-UnityEditor -Project ${{ parameters.PathToProject }} -Version ${{ parameters.UnityVersion }} -ExecuteMethod ${{ parameters.CommandLineBuildMethod }} -BatchMode -Quit -Wait -LogFile $logFile -BuildTarget ${{ parameters.BuildTarget }} -OutputPath ${{ parameters.OutputPath }} -AdditionalArguments "-CacheServerIPAddress ${Env:COG-UnityCache-WUS2-01} ${{ parameters.AdditionalArguments }}"
    if (Test-Path $logFile)
    {
      Get-Content $logFile
    }
  displayName: Build ${{ parameters.BuildTarget }}
