# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# [Template] Build project inside Unity.

parameters:
- name: UnityVersion
  type: string

- name: BuildTarget
  type: string
  values:
    - StandaloneWindows64
    - WSAPlayer
    - Android

- name: CommandLineBuildMethod
  type: string

- name: PathToProject
  type: string

- name: OutputPath
  type: string

- name: AdditionalArguments
  type: string
  default: ''

steps:
- pwsh: |
    $logFile = Join-Path $(Agent.TempDirectory) "build_${{ parameters.BuildTarget }}.log"
    New-Item -Path $logFile -ItemType File -Force
    if ("${{ parameters.UnityVersion }}" -eq "Latest") {
      $proc = Start-UnityEditor -Project "${{ parameters.PathToProject }}" -Latest -ExecuteMethod ${{ parameters.CommandLineBuildMethod }} -BatchMode -Quit -PassThru -LogFile $logFile -BuildTarget ${{ parameters.BuildTarget }} -OutputPath "${{ parameters.OutputPath }}" -AdditionalArguments "${{ parameters.AdditionalArguments }}"
    }
    else {
      $proc = Start-UnityEditor -Project "${{ parameters.PathToProject }}" -Version ${{ parameters.UnityVersion }} -ExecuteMethod ${{ parameters.CommandLineBuildMethod }} -BatchMode -Quit -PassThru -LogFile $logFile -BuildTarget ${{ parameters.BuildTarget }} -OutputPath "${{ parameters.OutputPath }}" -AdditionalArguments "${{ parameters.AdditionalArguments }}"
    }
    $ljob = Start-Job -ScriptBlock { param($log) Get-Content "$log" -Wait } -ArgumentList $logFile

    while (-not $proc.HasExited -and $ljob.HasMoreData) {
        Receive-Job $ljob
        Start-Sleep -Milliseconds 200
    }

    Stop-Job $ljob
    Remove-Job $ljob
    Stop-Process $proc

    Write-Output '====================================================='
    Write-Output '             Unity Build Player Finished             '
    Write-Output '====================================================='

    if (Test-Path $logFile) {
        Write-Output '====================================================='
        Write-Output '               Begin Unity Player Log                '
        Write-Output '====================================================='

        Get-Content $logFile

        Write-Output '====================================================='
        Write-Output '                End Unity Player Log                 '
        Write-Output '====================================================='
    }
    else {
        Write-Output 'Unity Player log missing!'
    }

    if ($proc.ExitCode -ne 0) {
        exit $proc.ExitCode
    }
  displayName: Build ${{ parameters.BuildTarget }}
