# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# [Template] Build appx from a Unity-built sln.

parameters:
- name: ProjectName
  type: string

- name: Architectures
  type: object
  default: []

- name: BuildFolderPath
  type: string

steps:
- ${{ each arch in parameters.Architectures }}:
  - task: MSBuild@1
    displayName: Build ${{ arch }} AppX
    inputs:
      solution: ${{ parameters.BuildFolderPath }}/${{ parameters.ProjectName }}.sln
      platform: ${{ arch }}
      configuration: Master

  - task: CopyFiles@2
    displayName: Copy ${{ arch }} AppX to artifacts staging directory
    inputs:
      ${{ if eq(arch, 'x86') }}:
        sourceFolder: ${{ parameters.BuildFolderPath }}/AppPackages/${{ parameters.ProjectName }}/${{ parameters.ProjectName }}_$(MRTKVersion).0_Win32_Master_Test
      ${{ if not(eq(arch, 'x86')) }}:
        sourceFolder: ${{ parameters.BuildFolderPath }}/AppPackages/${{ parameters.ProjectName }}/${{ parameters.ProjectName }}_$(MRTKVersion).0_${{ arch }}_Master_Test
      targetFolder: $(Build.ArtifactStagingDirectory)/Apps/uwp-${{ arch }}
