# [Template] Build appx from a Unity-built sln.

parameters:
- name: ProjectName
  type: string

- name: Architectures
  type: object
  default: []

- name: BuildFolderPath
  type: string

- name: OutputPath
  type: string

steps:
- ${{ each arch in parameters.Architectures }}:
  - task: MSBuild@1
    displayName: Build ${{ arch }} AppX
    inputs:
      solution: ${{ parameters.BuildFolderPath }}/${{ parameters.ProjectName }}.sln
      platform: ${{ arch }}
      configuration: Master

  - task: CopyFiles@2
    displayName: Copy ${{ arch }} AppX to ${{ parameters.OutputPath }}
    inputs:
      sourceFolder: ${{ parameters.BuildFolderPath }}/AppPackages/${{ parameters.ProjectName }}/${{ parameters.ProjectName }}_$(MRTKVersion).0_${{ arch }}_Master_Test
      targetFolder: ${{ parameters.OutputPath }}
