# [Template] Create NuGet packages.

parameters:
  Sign: false

steps:
- task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: 'NuGet/**/*.nuspec'
    packDestination: '$(Build.SourcesDirectory)/artifacts'
    buildProperties: 'version=$(MRTKVersion)-$(Build.BuildNumber)'

- ${{ if parameters.Sign }}:
  - template: tasks/signing.yml
    parameters:
      ConfigName: "MRTKNuGetSignConfig.xml"

- task: PublishBuildArtifacts@1
  displayName: 'Publish Packages'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\artifacts'
    ArtifactName: 'mrtk-unity-packages'

- task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '$(Build.SourcesDirectory)/artifacts/**/*.nupkg;!$(Build.SourcesDirectory)/artifacts/**/*.symbols.nupkg'
    publishVstsFeed: '$(NuGetFeedId)'
    buildProperties: 'version=$(MRTKVersion)-$(Build.BuildNumber)'
