//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace HoloToolkit.Sharing {

public enum MessageReliability {
  Unreliable = 0,
  UnreliableSequenced,
  Reliable,
  ReliableOrdered,
  ReliableSequenced
}

}
