//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace HoloToolkit.Sharing {

public enum MessageChannel {
  Default = 0,
  Mouse,
  Avatar,
  Audio,
  ProfileChannel,
  RoomAnchorChannel,
  UserMessageChannelStart = 16,
  MessageChannelMax = 31
}

}
