# CI build for developer builds.

variables:
- template: config/settings.yml
- name: packagingEnabled
  value: false

jobs:
- job: Unity2019Validation
  timeoutInMinutes: 120
  pool:
    name: On-Prem Unity
    demands:
    - ${{ variables.Unity2019Version }}
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
    - VS2019 -equals TRUE
  steps:
  - template: templates/common.yml
    parameters:
      UnityVersion: $(Unity2019Version)
      buildUWPArm64: true

- job: Unity2018Validation
  timeoutInMinutes: 120
  pool:
    name: On-Prem Unity
    demands:
    - ${{ variables.Unity2018Version }}
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - template: templates/ci-common.yml
    parameters:
      packagingEnabled: false
      UnityVersion: $(Unity2018Version)
