# CI build producing developer packages.

variables:
- template: config/settings.yml

jobs:
- job: CIDeveloperValidation
  timeoutInMinutes: 90
  pool:
    name: On-Prem Unity
    demands:
    - ${{ variables.Unity2018Version }}
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - template: templates/ci-common.yml
    parameters:
        UnityVersion: $(Unity2018Version)
