# CI build producing developer packages.

variables:
- template: config/settings.yml

jobs:
- job: CodeValidation
  pool:
    vmImage: windows-2019
  steps:
  - template: templates/validation.yml

- job: UnityValidation
  timeoutInMinutes: 90
  pool:
    name: Analog On-Prem
    demands:
    - ${{ variables.Unity2018VersionInternal }}
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  workspace:
    clean: resources
  steps:
  - template: templates/ci-common.yml
    parameters:
      publishPackagesToFeed: true
      UnityVersion: $(Unity2018VersionInternal)
