# CI build producing developer packages.

variables:
- template: config/settings.yml

jobs:
- job: CodeValidation
  pool:
    vmImage: windows-latest
  steps:
  - template: templates/validation.yml

- job: UnityValidation
  timeoutInMinutes: 90
  pool:
    name: Analog-Unity
    demands:
      - ImageVersionOverride -equals 20220218.0.1
  workspace:
    clean: resources
  steps:
  - template: templates/ci-common.yml
    parameters:
      publishPackagesToFeed: true
      UnityVersion: $(Unity2019VersionInternal)

  - pwsh: Write-Host "##vso[build.updatebuildnumber]$(MRTKVersion)-preview.$(Build.BuildNumber)"
    displayName: Set build number
