# CI build producing developer packages.

variables:
- template: config/settings.yml

jobs:
- job: CIDeveloperValidation
  timeoutInMinutes: 90
  pool:
    name: Analog On-Prem
    demands:
    - Unity2018.4.23f1
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - template: templates/ci-common.yml
    parameters:
      packagingEnabled: true
      packagePublishing: true
      UnityVersion: $(Unity2018VersionInternal)
      MRTKVersion: $(MRTKVersion)
