# CI build for developer builds.

variables:
  UnityVersion: Unity2018.3.7f1
  MRTKVersion: 2.0.0

jobs:
- job: CIDeveloperValidation
  timeoutInMinutes: 90
  pool:
    name: On-Prem Unity
    demands:
    - Unity2018.3.7f1
  steps:
  - template: templates/common.yml
  - template: templates/package.yml
  - template: templates/end.yml
