# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# CI build producing developer packages.

variables:
- template: Config/settings.yaml
- name: Version.Revision
  value: $[counter(variables['MRTKVersion'], 1)]
- name: Version.PreReleaseRevision
  value: $[counter(variables['MRTKReleaseTag'], 1)]

resources:
  repositories:
  - repository: PipelineTools
    type: git
    endpoint: ToolsAccess
    name: tools.internal
    ref: 78ecf591964ecf511b4c7a0cd84d98ce11e8be16
  - repository: DocToolUnityProject
    type: git
    endpoint: ToolsAccess
    name: lib.doctools
    ref: f6dcb5efd248fbe486757cb5a7198aed81c180d5

pr: none # disable PR validation

jobs:
- job: UnityValidation
  pool: Unity_2021.3.3f1_Pool
  steps:
  - checkout: self

  - checkout: PipelineTools

  - pwsh: Write-Host "##vso[build.updatebuildnumber]$(MRTKVersion)-$(MRTKReleaseTag).$(Version.PreReleaseRevision)"
    displayName: 'Set Build Number'

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      alertWarningLevel: 'Medium'
      failOnAlert: true

  - template: Templates/unity.yaml
    parameters:
      BuildStandalone: true
      BuildUWP: true
      BuildAndroid: true

  - template: Templates/upm.yaml
    parameters:
      buildNumber: $(Version.Revision)
      previewTag: $(MRTKReleaseTag).$(Version.PreReleaseRevision)
      publishToFeed: true

- job: DocsBinariesGeneration
  pool: Unity_2021.3.3f1_Pool
  steps:
  - checkout: self

  - checkout: PipelineTools

  - checkout: DocToolUnityProject

  - template: Templates/license-unity.yaml@PipelineTools

  - template: Templates/docs.yaml