# CI build for developer builds.

variables:
- template: config/settings.yml
- name: packagingEnabled
  value: false

jobs:
- job: CIDeveloperValidation
  timeoutInMinutes: 120
  pool:
    name: On-Prem Unity
    demands:
    - Unity2018.4.26f1
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - template: templates/ci-common.yml
    parameters:
      packagingEnabled: false
      UnityVersion: $(Unity2018Version)
      MRTKVersion: $(MRTKVersion)
