# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Build for PR validation

variables:
- template: Config/settings.yaml

resources:
  repositories:
  - repository: BuildTools
    type: git
    name: tools.internal

trigger: none # disable CI

jobs:
- job: UnityValidation
  pool: Unity_2021.3.3f1_Pool
  steps:
  - checkout: self
    clean: true
    fetchDepth: 3

  - checkout: BuildTools

  - script: dir $(Build.SourcesDirectory)

  # - template: Templates/unity.yaml
