# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Build for PR validation

variables:
- template: Config/settings.yaml

resources:
  repositories:
  - repository: PipelineTools
    type: git
    endpoint: ToolsAccess
    name: tools.internal
    ref: 78ecf591964ecf511b4c7a0cd84d98ce11e8be16

trigger: none # disable CI

jobs:
- job: UnityValidation
  pool: Unity_2021.3.3f1_Pool
  steps:
  - checkout: self
    fetchDepth: 3

  - checkout: PipelineTools

  - template: Templates/unity.yaml
    parameters:
      BuildStandalone: true
      BuildUWP: true