/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace HoloToolkit.XTools {

public enum MessageID {
  Start = 134,
  StatusOnly = Start,
  Broadcast,
  SessionStatus,
  SessionControl,
  MouseXToClient,
  MouseXToServer,
  SyncMessage,
  Tunnel,
  TunnelControl,
  AudioSamples,
  Handshake,
  UserPresenceChange,
  AvatarBroadcast,
  TestAutomation,
  Profiling,
  UserMessageIDStart = 134+50
}

}
