/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace HoloToolkit.XTools {

public class NetworkConnection : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetworkConnection(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetworkConnection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetworkConnection() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XToolsClientPINVOKE.delete_NetworkConnection(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool IsConnected() {
    bool ret = XToolsClientPINVOKE.NetworkConnection_IsConnected(swigCPtr);
    return ret;
  }

  public virtual ulong GetConnectionGUID() {
    ulong ret = XToolsClientPINVOKE.NetworkConnection_GetConnectionGUID(swigCPtr);
    return ret;
  }

  public virtual void Send(NetworkOutMessage msg, MessagePriority priority, MessageReliability reliability, MessageChannel channel, bool releaseMessage) {
    XToolsClientPINVOKE.NetworkConnection_Send__SWIG_0(swigCPtr, NetworkOutMessage.getCPtr(msg), (int)priority, (int)reliability, (int)channel, releaseMessage);
  }

  public virtual void Send(NetworkOutMessage msg, MessagePriority priority, MessageReliability reliability, MessageChannel channel) {
    XToolsClientPINVOKE.NetworkConnection_Send__SWIG_1(swigCPtr, NetworkOutMessage.getCPtr(msg), (int)priority, (int)reliability, (int)channel);
  }

  public virtual void Send(NetworkOutMessage msg, MessagePriority priority, MessageReliability reliability) {
    XToolsClientPINVOKE.NetworkConnection_Send__SWIG_2(swigCPtr, NetworkOutMessage.getCPtr(msg), (int)priority, (int)reliability);
  }

  public virtual void Send(NetworkOutMessage msg, MessagePriority priority) {
    XToolsClientPINVOKE.NetworkConnection_Send__SWIG_3(swigCPtr, NetworkOutMessage.getCPtr(msg), (int)priority);
  }

  public virtual void Send(NetworkOutMessage msg) {
    XToolsClientPINVOKE.NetworkConnection_Send__SWIG_4(swigCPtr, NetworkOutMessage.getCPtr(msg));
  }

  public virtual void Broadcast(NetworkOutMessage msg, MessagePriority priority, MessageReliability reliability, MessageChannel channel, bool releaseMessage) {
    XToolsClientPINVOKE.NetworkConnection_Broadcast__SWIG_0(swigCPtr, NetworkOutMessage.getCPtr(msg), (int)priority, (int)reliability, (int)channel, releaseMessage);
  }

  public virtual void Broadcast(NetworkOutMessage msg, MessagePriority priority, MessageReliability reliability, MessageChannel channel) {
    XToolsClientPINVOKE.NetworkConnection_Broadcast__SWIG_1(swigCPtr, NetworkOutMessage.getCPtr(msg), (int)priority, (int)reliability, (int)channel);
  }

  public virtual void Broadcast(NetworkOutMessage msg, MessagePriority priority, MessageReliability reliability) {
    XToolsClientPINVOKE.NetworkConnection_Broadcast__SWIG_2(swigCPtr, NetworkOutMessage.getCPtr(msg), (int)priority, (int)reliability);
  }

  public virtual void Broadcast(NetworkOutMessage msg, MessagePriority priority) {
    XToolsClientPINVOKE.NetworkConnection_Broadcast__SWIG_3(swigCPtr, NetworkOutMessage.getCPtr(msg), (int)priority);
  }

  public virtual void Broadcast(NetworkOutMessage msg) {
    XToolsClientPINVOKE.NetworkConnection_Broadcast__SWIG_4(swigCPtr, NetworkOutMessage.getCPtr(msg));
  }

  public virtual void AddListener(byte messageType, NetworkConnectionListener newListener) {
    XToolsClientPINVOKE.NetworkConnection_AddListener(swigCPtr, messageType, NetworkConnectionListener.getCPtr(newListener));
  }

  public virtual void RemoveListener(byte messageType, NetworkConnectionListener oldListener) {
    XToolsClientPINVOKE.NetworkConnection_RemoveListener(swigCPtr, messageType, NetworkConnectionListener.getCPtr(oldListener));
  }

  public virtual bool RegisterAsyncCallback(byte messageType, NetworkConnectionListener cb) {
    bool ret = XToolsClientPINVOKE.NetworkConnection_RegisterAsyncCallback(swigCPtr, messageType, NetworkConnectionListener.getCPtr(cb));
    return ret;
  }

  public virtual void UnregisterAsyncCallback(byte messageType) {
    XToolsClientPINVOKE.NetworkConnection_UnregisterAsyncCallback(swigCPtr, messageType);
  }

  public virtual NetworkOutMessage CreateMessage(byte messageType) {
    global::System.IntPtr cPtr = XToolsClientPINVOKE.NetworkConnection_CreateMessage(swigCPtr, messageType);
    NetworkOutMessage ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetworkOutMessage(cPtr, true);
    return ret; 
  }

  public virtual void ReturnMessage(NetworkOutMessage msg) {
    XToolsClientPINVOKE.NetworkConnection_ReturnMessage(swigCPtr, NetworkOutMessage.getCPtr(msg));
  }

  public virtual void Disconnect() {
    XToolsClientPINVOKE.NetworkConnection_Disconnect(swigCPtr);
  }

  public virtual XString GetRemoteAddress() {
    global::System.IntPtr cPtr = XToolsClientPINVOKE.NetworkConnection_GetRemoteAddress(swigCPtr);
    XString ret = (cPtr == global::System.IntPtr.Zero) ? null : new XString(cPtr, true);
    return ret; 
  }

}

}
