/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace HoloToolkit.XTools {

public class XToolsClient {
  public static ulong kInvalidSocketID {
    get {
      ulong ret = XToolsClientPINVOKE.kInvalidSocketID_get();
      return ret;
    } 
  }

  public static ulong kInvalidConnectionGUID {
    get {
      ulong ret = XToolsClientPINVOKE.kInvalidConnectionGUID_get();
      return ret;
    } 
  }

  public static long kInvalidXGuid {
    get {
      long ret = XToolsClientPINVOKE.kInvalidXGuid_get();
      return ret;
    } 
  }

}

}
