// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using UnityEngine.EventSystems;

namespace HoloToolkit.Unity.InputModule
{
    /// <summary>
    /// Describes a Unity pointer event that was generated by a specific input source and ID.
    /// </summary>
    public class PointerInputEventData :
        PointerEventData,
        IInputSourceInfoProvider
    {
        public IInputSource InputSource { get; set; }

        public uint SourceId { get; set; }

        public PointerInputEventData(EventSystem eventSystem) : base(eventSystem)
        {
        }
    }
}