name: "PR Labeling"
on:
  pull_request_target:
    types: [opened, closed, synchronize, reopened, edited, ready_for_review]
  
permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.pull_request.base.ref == 'mrtk3')
            {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['MRTK3']
              })
            }

            // When we switch the repo to MRTK3, we'll have to edit this.
            if (context.payload.pull_request.base.ref == 'main')
            {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['MRTK2']
              })
            }