//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MixedRealityToolkit.Sharing {

public class DoubleElement : Element {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DoubleElement(global::System.IntPtr cPtr, bool cMemoryOwn) : base(SharingClientPINVOKE.DoubleElement_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DoubleElement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DoubleElement() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SharingClientPINVOKE.delete_DoubleElement(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static DoubleElement Cast(Element element) {
    global::System.IntPtr cPtr = SharingClientPINVOKE.DoubleElement_Cast(Element.getCPtr(element));
    DoubleElement ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleElement(cPtr, true);
    return ret; 
  }

  public virtual double GetValue() {
    double ret = SharingClientPINVOKE.DoubleElement_GetValue(swigCPtr);
    return ret;
  }

  public virtual void SetValue(double newValue) {
    SharingClientPINVOKE.DoubleElement_SetValue(swigCPtr, newValue);
  }

}

}
