//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MixedRealityToolkit.Sharing {

public enum ElementType {
  UnknownType = 0,
  BoolType,
  Int32Type,
  Int64Type,
  FloatType,
  DoubleType,
  StringType,
  ObjectType,
  Int32ArrayType,
  FloatArrayType,
  StringArrayType,
  ElementTypeCount
}

}
