//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

#if WINDOWS_UWP
using MixedRealityToolkit.Common.Extensions;
#endif

namespace MixedRealityToolkit.Sharing {

public class LogWriter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LogWriter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LogWriter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LogWriter() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SharingClientPINVOKE.delete_LogWriter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void WriteLogEntry(LogSeverity severity, string message) {
    if (SwigDerivedClassHasMethod("WriteLogEntry", swigMethodTypes0)) SharingClientPINVOKE.LogWriter_WriteLogEntrySwigExplicitLogWriter(swigCPtr, (int)severity, message); else SharingClientPINVOKE.LogWriter_WriteLogEntry(swigCPtr, (int)severity, message);
    if (SharingClientPINVOKE.SWIGPendingException.Pending) throw SharingClientPINVOKE.SWIGPendingException.Retrieve();
  }

  public LogWriter() : this(SharingClientPINVOKE.new_LogWriter(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("WriteLogEntry", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateLogWriter_0(SwigDirectorWriteLogEntry);
    SharingClientPINVOKE.LogWriter_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(LogWriter));
    return hasDerivedMethod;
  }

  private void SwigDirectorWriteLogEntry(int severity, string message) {
    WriteLogEntry((LogSeverity)severity, message);
  }

  public delegate void SwigDelegateLogWriter_0(int severity, string message);

  private SwigDelegateLogWriter_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(LogSeverity), typeof(string) };
}

}
