//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MixedRealityToolkit.Sharing {

public enum MessageID {
  Start = 134,
  StatusOnly = Start,
  Broadcast,
  SendTo,
  SessionControl,
  MouseXToClient,
  MouseXToServer,
  SyncMessage,
  Tunnel,
  TunnelControl,
  AudioSamples,
  Handshake,
  UserPresenceChange,
  AvatarBroadcast,
  TestAutomation,
  Profiling,
  InternalSyncMessage,
  RoomAnchor,
  UserMessageIDStart = 134+50
}

}
