//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MixedRealityToolkit.Sharing {

public class SharingClient {
  public static ulong kInvalidSocketID {
    get {
      ulong ret = SharingClientPINVOKE.kInvalidSocketID_get();
      return ret;
    } 
  }

  public static ulong kInvalidConnectionGUID {
    get {
      ulong ret = SharingClientPINVOKE.kInvalidConnectionGUID_get();
      return ret;
    } 
  }

  public static long kInvalidXGuid {
    get {
      long ret = SharingClientPINVOKE.kInvalidXGuid_get();
      return ret;
    } 
  }

}

}
